### ISSUE TITLE
Precision with Umlauts and without

### ISSUE THREAD

**Issue by NebelAI** [PhilipMay/german-transformer-training#1]
Hello,

in your model card at hugginface transfomers you say `"The special characters 'ö', 'ü', 'ä' are included through the strip_accent=False option, as this leads to an improved precision."` (source: https://huggingface.co/german-nlp-group/electra-base-german-uncased). Can you tell me how much better the precision is?

Thank you in advance.

**Comment by PhilipMay** [comment]
No we can not since we did not train a full model without umlauts. But since the umlauts can have a stong semantic meaning in German language the effect can be strong. But as always it depends on the usecase.
