### ISSUE TITLE
 electra-base-german-uncased as TF model?

### ISSUE THREAD

**Issue by mawic** [PhilipMay/german-transformer-training#3]
Do you plan to release also a TF model of electra-base-german-uncased? I played around with the pytorch model and I was realy impressed. But I need a TF model because I want to use it in R. Thanks!

**Comment by PhilipMay** [comment]
You can just download the full checkpoint (generator + discr.) of the training: https://huggingface.co/german-nlp-group/electra-base-german-uncased/resolve/main/ckpt-1500000.tar.gz

From there on I am not 100% sure how to proceed but it should be possible to convert that into the TF language modek from HF.
